[package]
name = "simmy-dimmy"
version = "0.0.1"
authors = ["Simon Salloum"]
edition = "2018"

[dependencies]
rand = "0.6.5"
colored = "1.8"
itertools = "0.8"
uuid = { version = "0.7.4", features = ["serde", "v4"] }